{
  "public_data_at_usn": "0001-01-01T00:00:00Z",
  "crd": "0001-01-01T00:00:00Z",
  "candidate": "CVE-2020-36244",
  "public_date": "2021-02-10T07:15:00Z",
  "references": [
    {
      "reference": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36244"
    },
    {
      "reference": "https://github.com/GENIVI/dlt-daemon/issues/265"
    },
    {
      "reference": "https://github.com/GENIVI/dlt-daemon/pull/269"
    },
    {
      "reference": "https://github.com/GENIVI/dlt-daemon/commit/af734fe097ed379b0aa5fcf551886b1ce5098052 (v2.18.6)"
    },
    {
      "reference": "https://github.com/GENIVI/dlt-daemon/compare/v2.18.5...v2.18.6"
    }
  ],
  "description": "The daemon in GENIVI diagnostic log and trace (DLT), is vulnerable to a heap-based buffer overflow that could allow an attacker to remotely execute arbitrary code on the DLT-Daemon (versions prior to 2.18.6).",
  "ubuntu_description": "",
  "notes": [],
  "bugs": [],
  "priority": "medium",
  "discovered_by": "",
  "assigned_to": "",
  "patches": [
    {
      "package_name": "dlt-daemon",
      "release_patches": [
        {
          "release_name": "trusty",
          "status": "ignored",
          "note": "out of standard support"
        }
      ]
    }
  ],
  "upstreams": []
}
