{
  "public_data_at_usn": "0001-01-01T00:00:00Z",
  "crd": "0001-01-01T00:00:00Z",
  "candidate": "CVE-2019-6442",
  "public_date": "2019-01-16T05:29:00Z",
  "references": [
    {
      "reference": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-6442"
    },
    {
      "reference": "https://dumpco.re/blog/ntpsec-bugs"
    },
    {
      "reference": "https://dumpco.re/bugs/ntpsec-authed-oobwrite"
    },
    {
      "reference": "https://github.com/ntpsec/ntpsec/blob/NTPsec_1_1_3/NEWS"
    },
    {
      "reference": "https://www.exploit-db.com/exploits/46178/"
    }
  ],
  "description": "An issue was discovered in NTPsec before 1.1.3. An authenticated attacker can write one byte out of bounds in ntpd via a malformed config request, related to config_remotely in ntp_config.c, yyparse in ntp_parser.tab.c, and yyerror in ntp_parser.y.",
  "ubuntu_description": "",
  "notes": [],
  "bugs": [
    {
      "bug": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=919513"
    },
    {
      "bug": "https://bugs.launchpad.net/ubuntu/+source/ntpsec/+bug/1812458"
    }
  ],
  "priority": "medium",
  "discovered_by": "",
  "assigned_to": "",
  "patches": [
    {
      "package_name": "ntpsec",
      "release_patches": [
        {
          "release_name": "trusty",
          "status": "DNE",
          "note": ""
        }
      ]
    }
  ],
  "upstreams": []
}
