[
  {
    "DefinitionID": "oval:org.debian:def:16638678165757071445884192749026780617",
    "Title": "CVE-2016-1000110 python2.7",
    "Description": "The CGIHandler class in Python before 2.7.12 does not protect against the HTTP_PROXY variable name clash in a CGI script, which could allow a remote attacker to redirect HTTP requests.",
    "Advisory": {
      "Severity": "",
      "Cves": [
        {
          "CveID": "CVE-2016-1000110",
          "Cvss2": "",
          "Cvss3": "",
          "Cwe": "",
          "Impact": "",
          "Href": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-1000110",
          "Public": ""
        }
      ],
      "Bugzillas": [],
      "AffectedCPEList": [],
      "Issued": "1000-01-01T00:00:00Z",
      "Updated": "1000-01-01T00:00:00Z"
    },
    "Debian": {
      "MoreInfo": "",
      "Date": "1000-01-01T00:00:00Z"
    },
    "AffectedPacks": [
      {
        "Name": "python2.7",
        "Version": "2.7.12-2",
        "Arch": "",
        "NotFixedYet": false,
        "ModularityLabel": ""
      }
    ],
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2016-1000110",
        "RefURL": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-1000110"
      }
    ]
  },
  {
    "DefinitionID": "oval:org.debian:def:219370690331359668935117670052161340518",
    "Title": "CVE-2016-1000110 python3.5",
    "Description": "The CGIHandler class in Python before 2.7.12 does not protect against the HTTP_PROXY variable name clash in a CGI script, which could allow a remote attacker to redirect HTTP requests.",
    "Advisory": {
      "Severity": "",
      "Cves": [
        {
          "CveID": "CVE-2016-1000110",
          "Cvss2": "",
          "Cvss3": "",
          "Cwe": "",
          "Impact": "",
          "Href": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-1000110",
          "Public": ""
        }
      ],
      "Bugzillas": [],
      "AffectedCPEList": [],
      "Issued": "1000-01-01T00:00:00Z",
      "Updated": "1000-01-01T00:00:00Z"
    },
    "Debian": {
      "MoreInfo": "",
      "Date": "1000-01-01T00:00:00Z"
    },
    "AffectedPacks": [
      {
        "Name": "python3.5",
        "Version": "3.5.2-3",
        "Arch": "",
        "NotFixedYet": false,
        "ModularityLabel": ""
      }
    ],
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2016-1000110",
        "RefURL": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-1000110"
      }
    ]
  }
]
