[
  {
    "DefinitionID": "oval:com.redhat.rhsa:def:20193520",
    "Title": "RHSA-2019:3520: python3 security and bug fix update (Moderate)",
    "Description": "Python is an interpreted, interactive, object-oriented programming language, which includes modules, classes, exceptions, very high level dynamic data types and dynamic typing. Python supports interfaces to many system calls and libraries, as well as to various windowing systems.\n\nSecurity Fix(es):\n\n* python: NULL pointer dereference using a specially crafted X509 certificate (CVE-2019-5010)\n\n* python: CRLF injection via the query part of the url passed to urlopen() (CVE-2019-9740)\n\n* python: CRLF injection via the path part of the url passed to urlopen() (CVE-2019-9947)\n\n* python: Undocumented local_file protocol allows remote attackers to bypass protection mechanisms (CVE-2019-9948)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.\n\nAdditional Changes:\n\nFor detailed information on changes in this release, see the Red Hat Enterprise Linux 8.1 Release Notes linked from the References section.",
    "Advisory": {
      "Severity": "Moderate",
      "Cves": [
        {
          "CveID": "CVE-2019-5010",
          "Cvss2": "",
          "Cvss3": "7.5/CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "Cwe": "CWE-476",
          "Impact": "moderate",
          "Href": "https://access.redhat.com/security/cve/CVE-2019-5010",
          "Public": "20190115"
        }
      ],
      "Bugzillas": [
        {
          "BugzillaID": "1666519",
          "URL": "https://bugzilla.redhat.com/1666519",
          "Title": "CVE-2019-5010 python: NULL pointer dereference using a specially crafted X509 certificate"
        },
        {
          "BugzillaID": "1688169",
          "URL": "https://bugzilla.redhat.com/1688169",
          "Title": "CVE-2019-9740 python: CRLF injection via the query part of the url passed to urlopen()"
        },
        {
          "BugzillaID": "1695570",
          "URL": "https://bugzilla.redhat.com/1695570",
          "Title": "CVE-2019-9948 python: Undocumented local_file protocol allows remote attackers to bypass protection mechanisms"
        },
        {
          "BugzillaID": "1695572",
          "URL": "https://bugzilla.redhat.com/1695572",
          "Title": "CVE-2019-9947 python: CRLF injection via the path part of the url passed to urlopen()"
        }
      ],
      "AffectedCPEList": [
        {
          "Cpe": "cpe:/a:redhat:enterprise_linux:8"
        },
        {
          "Cpe": "cpe:/a:redhat:enterprise_linux:8::appstream"
        },
        {
          "Cpe": "cpe:/o:redhat:enterprise_linux:8"
        },
        {
          "Cpe": "cpe:/o:redhat:enterprise_linux:8::baseos"
        }
      ],
      "Issued": "2019-11-05T00:00:00Z",
      "Updated": "2019-11-05T00:00:00Z"
    },
    "Debian": null,
    "AffectedPacks": [
      {
        "Name": "platform-python",
        "Version": "0:3.6.8-15.1.el8",
        "Arch": "",
        "NotFixedYet": false,
        "ModularityLabel": ""
      },
      {
        "Name": "platform-python-debug",
        "Version": "0:3.6.8-15.1.el8",
        "Arch": "",
        "NotFixedYet": false,
        "ModularityLabel": ""
      },
      {
        "Name": "platform-python-devel",
        "Version": "0:3.6.8-15.1.el8",
        "Arch": "",
        "NotFixedYet": false,
        "ModularityLabel": ""
      },
      {
        "Name": "python3-idle",
        "Version": "0:3.6.8-15.1.el8",
        "Arch": "",
        "NotFixedYet": false,
        "ModularityLabel": ""
      },
      {
        "Name": "python3-libs",
        "Version": "0:3.6.8-15.1.el8",
        "Arch": "",
        "NotFixedYet": false,
        "ModularityLabel": ""
      },
      {
        "Name": "python3-test",
        "Version": "0:3.6.8-15.1.el8",
        "Arch": "",
        "NotFixedYet": false,
        "ModularityLabel": ""
      },
      {
        "Name": "python3-tkinter",
        "Version": "0:3.6.8-15.1.el8",
        "Arch": "",
        "NotFixedYet": false,
        "ModularityLabel": ""
      }
    ],
    "References": [
      {
        "Source": "RHSA",
        "RefID": "RHSA-2019:3520",
        "RefURL": "https://access.redhat.com/errata/RHSA-2019:3520"
      },
      {
        "Source": "CVE",
        "RefID": "CVE-2019-5010",
        "RefURL": "https://access.redhat.com/security/cve/CVE-2019-5010"
      },
      {
        "Source": "CVE",
        "RefID": "CVE-2019-9740",
        "RefURL": "https://access.redhat.com/security/cve/CVE-2019-9740"
      },
      {
        "Source": "CVE",
        "RefID": "CVE-2019-9947",
        "RefURL": "https://access.redhat.com/security/cve/CVE-2019-9947"
      },
      {
        "Source": "CVE",
        "RefID": "CVE-2019-9948",
        "RefURL": "https://access.redhat.com/security/cve/CVE-2019-9948"
      }
    ]
  }
]
