{
  "public_data_at_usn": "0001-01-01T00:00:00Z",
  "crd": "0001-01-01T00:00:00Z",
  "candidate": "CVE-2020-11653",
  "public_date": "2020-04-08T23:15:00Z",
  "references": [
    {
      "reference": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-11653"
    },
    {
      "reference": "https://varnish-cache.org/security/VSV00005.html#vsv00005"
    },
    {
      "reference": "https://github.com/varnishcache/varnish-cache/commit/2d8fc1a784a1e26d78c30174923a2b14ee2ebf62"
    }
  ],
  "description": "An issue was discovered in Varnish Cache before 6.0.6 LTS, 6.1.x and 6.2.x before 6.2.3, and 6.3.x before 6.3.2. It occurs when communication with a TLS termination proxy uses PROXY version 2. There can be an assertion failure and daemon restart, which causes a performance loss.",
  "ubuntu_description": "",
  "notes": [],
  "bugs": [
    {
      "bug": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=956307"
    }
  ],
  "priority": "low",
  "discovered_by": "",
  "assigned_to": "",
  "patches": [
    {
      "package_name": "varnish",
      "release_patches": [
        {
          "release_name": "bionic",
          "status": "needs-triage",
          "note": ""
        }
      ]
    }
  ],
  "upstreams": []
}
