{
  "public_data_at_usn": "0001-01-01T00:00:00Z",
  "crd": "0001-01-01T00:00:00Z",
  "candidate": "CVE-2017-9814",
  "public_date": "2017-07-17T13:18:00Z",
  "references": [
    {
      "reference": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-9814"
    }
  ],
  "description": "cairo-truetype-subset.c in cairo 1.15.6 and earlier allows remote attackers to cause a denial of service (out-of-bounds read) because of mishandling of an unexpected malloc(0) call.",
  "ubuntu_description": "",
  "notes": [
    {
      "note": "mdeslaur\u003e as of 2020-11-26, no complete fix from upstream"
    }
  ],
  "bugs": [
    {
      "bug": "https://gitlab.freedesktop.org/cairo/cairo/issues/264 (main bug)"
    },
    {
      "bug": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=868580"
    },
    {
      "bug": "https://bugs.freedesktop.org/show_bug.cgi?id=101547"
    }
  ],
  "priority": "low",
  "discovered_by": "Alberto Garcia, Francisco Oca, Suleman Ali",
  "assigned_to": "",
  "patches": [
    {
      "package_name": "cairo",
      "release_patches": [
        {
          "release_name": "hirsute",
          "status": "deferred",
          "note": ""
        }
      ]
    }
  ],
  "upstreams": []
}
